language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
branches:
  except:
    - gh-pages
jdk:
  - oraclejdk8
install: true
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
notifications:
  email: false